export const userData = {
  userName: 'The Octocat',
  userHandle: '@octocat',
  userJoin: '25 Jan 2011',
  userImg: 'https://avatars.githubusercontent.com/u/583231?v=4',
  userBio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui eligendi asperiores quod id corrupti rem saepe a iusto est, necessitatibus nihil odio deleniti ut tenetur porro ipsum dolor!',
  userRepos: 8,
  userFollowers: 3938,
  userFollows: 9,
  userLocation: 'San Francisco',
  // userTwitterHandle: '@octocat',
  userTwitterLink: 'https://twitter.com',
  userLink: 'https://github.blog',
  userWork: '@github',
}